apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-frontend
  namespace: keycloak-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-frontend
  template:
    metadata:
      labels:
        app: js-frontend
    spec:
      containers:
        - name: js-frontend
          image: ghcr.io/austromo/kc-demo-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: js-frontend
  namespace: keycloak-prod
spec:
#  type: NodePort
  selector:
    app: js-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 32000
