apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak-prod
data:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME: "localhost"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://keycloak-db/db"
  KC_DB_USERNAME: "app"
  KC_DB_PASSWORD: "app"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
