apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  namespace: keycloak-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: postgres
          image: postgres:17.2
          env:
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_PASSWORD
              value: app
            - name: POSTGRES_DB
              value: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: keycloak-prod
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: keycloak-db
