apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-backend
  namespace: keycloak-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-backend
  template:
    metadata:
      labels:
        app: quarkus-backend
    spec:
      containers:
        - name: quarkus-backend
          image: ghcr.io/austromo/kc-demo-backend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-backend
  namespace: keycloak-prod
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: quarkus-backend
