services:
  keycloak:
    container_name: keycloak-demo
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=localhost
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HEALTH_ENABLED=true
    command: ["start-dev"]
#    volumes:  , "--import-realm"
#      - ./import:/opt/keycloak/data/import
    ports:
      - "8000:8080"
