services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./certs/certificate.crt:/etc/ssl/certificate.crt:ro
      - ./certs/private.key:/etc/ssl/private.key:ro
    restart: unless-stopped

  nginx-echo:
    image: nodstuff/gecho:latest
    restart: unless-stopped
