### Get realm roles
GET http://localhost:8080/admin/roles
Content-Type: */*

### Get realms
GET http://localhost:8080/admin/realms
Content-Type: */*

### Create realm
POST http://localhost:8080/admin/realms/new-realm
Content-Type: */*

### Delete realm
DELETE http://localhost:8080/admin/realms/new-realm
Content-Type: */*

### Create client in realm
POST http://localhost:8080/admin/realms/quarkus/client/quarkus-client
Content-Type: */*

### Delete client in realm
DELETE http://localhost:8080/admin/realms/quarkus/client/quarkus-client
Content-Type: */*
